/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userdetails;

import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Satwik Gupta
 */
public class UserDetailsUI extends javax.swing.JFrame {

    /**
     * Creates new form UserDetailsUI
     */
    Connection con;
    ResultSet rs;
    
    public void establishConnection(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_projects", "root", null);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Connection can not be established!");
            System.out.println("Connection can not be established due to: "+ex);
        }
    }
    
    public void displayTable(ResultSet rs){
        DefaultTableModel table = new DefaultTableModel();
        table = (DefaultTableModel)dataTable.getModel();
        table.setRowCount(0);
        try{
            while (rs.next()) {
                table.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
        } catch(Exception ex){
            System.out.println("Contact the dev: "+ex);
        }
    }
    
    public void displayTableAll(){
        try{
            PreparedStatement ps = con.prepareStatement("select * from users;");
            ResultSet r = ps.executeQuery();
            displayTable(r);
        } catch(Exception ex){
            System.out.println("Contact the dev: "+ex);
        }
    }
    
    public UserDetailsUI() {
        initComponents();
        establishConnection();
        displayTableAll();
        idLabel.setVisible(false);
        idTxt.setVisible(false);
        nameLabel.setVisible(false);
        nameTxt.setVisible(false);
        phnLabel.setVisible(false);
        phnTxt.setVisible(false);
        addLabel.setVisible(false);
        addTxt.setVisible(false);
        submitBtn.setVisible(false);
        homeBtn.setVisible(false);
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        insertBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        madeByLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        phnLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addLabel = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        phnTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        addTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel1.setText("User Details");

        insertBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        madeByLabel.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        madeByLabel.setText("Made By: Satwik Gupta");

        idLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idLabel.setText("ID:");

        phnLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        phnLabel.setText("Phone Number: ");

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nameLabel.setText("Name:");

        addLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addLabel.setText("Address:");

        idTxt.setColumns(5);
        idTxt.setMinimumSize(new java.awt.Dimension(4, 30));

        phnTxt.setColumns(10);
        phnTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnTxtActionPerformed(evt);
            }
        });

        nameTxt.setColumns(20);

        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        homeBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone Number", "Address"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(200, 523, Short.MAX_VALUE)
                            .addComponent(submitBtn))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(homeBtn)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(phnLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(idLabel)
                                            .addGap(54, 54, 54)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phnTxt)
                                        .addComponent(idTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addLabel)
                                        .addComponent(nameLabel))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addTxt)
                                .addComponent(nameTxt))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(madeByLabel)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(nameLabel)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phnLabel)
                    .addComponent(addLabel)
                    .addComponent(phnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(homeBtn))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(madeByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        idLabel.setVisible(true);
        idTxt.setVisible(true);
        submitBtn.setVisible(true);
        homeBtn.setVisible(true);
        submitBtn.setText("Delete");
        jScrollPane1.setVisible(true);
        
        madeByLabel.setVisible(false);
        insertBtn.setVisible(false);
        deleteBtn.setVisible(false);
        updateBtn.setVisible(false);
        searchBtn.setVisible(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void phnTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnTxtActionPerformed

    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String oper = submitBtn.getText();
        if(oper == "Insert"){
            String name = nameTxt.getText();
            String phn = phnTxt.getText();
            String add = addTxt.getText();
            try {
                int id = Integer.parseInt(idTxt.getText());
                PreparedStatement ps = con.prepareStatement("insert into users values(?,?,?,?);");
                ps.setInt(1, id);
                ps.setString(2, name);
                ps.setString(3, phn);
                ps.setString(4, add);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record inserted successfully!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Something went wrong. Call the ambulance!");
                System.out.println("Something went wrong. Please contact the developer with these details: "+ex);
            }
            nameTxt.setText("");
            idTxt.setText("");
            addTxt.setText("");
            phnTxt.setText("");
            displayTableAll();
        }
        else if(oper == "Delete"){
            int id = Integer.parseInt(idTxt.getText());
            try{
                PreparedStatement ps = con.prepareStatement("delete from users where id=?;");
                ps.setInt(1, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record deleted successfully!");
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(null,"Something went wrong. Call the ambulance!");
                System.out.println("Something went wrong. Please contact the developer with these details: "+ex);
            }
            idTxt.setText("");
            displayTableAll();
        }
        else if(oper == "Update"){
            String name = nameTxt.getText();
            String phn = phnTxt.getText();
            String add = addTxt.getText();
            int id = Integer.parseInt(idTxt.getText());
            try {
                PreparedStatement ps = con.prepareStatement("update users set name=?, phonenum=?, address=? where id=?");
                ps.setString(1, name);
                ps.setString(2, phn);
                ps.setString(3, add);
                ps.setInt(4, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record updated successfully!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Something went wrong. Call the ambulance!");
                System.out.println("Something went wrong. Please contact the developer with these details: "+ex);
            }
            nameTxt.setText("");
            idTxt.setText("");
            addTxt.setText("");
            phnTxt.setText("");
            displayTableAll();
        }
        else if(oper == "Search"){
            String name = nameTxt.getText();
            String phn = phnTxt.getText();
            String add = addTxt.getText();
            int id;
            if(idTxt.getText().isEmpty())
                id = 0;
            else
                id = Integer.parseInt(idTxt.getText());
            if(name == null)
                name="";
            if(phn == null)
                phn="";
            if(add == null)
                add="";
            try {
                PreparedStatement ps = con.prepareStatement("select * from users where name=? or phonenum=? or address=? or id=?");
                ps.setString(1, name);
                ps.setString(2, phn);
                ps.setString(3, add);
                ps.setInt(4, id);
                rs = ps.executeQuery();
//                while(rs.next()){
//                    System.out.println("ID: "+rs.getInt(1)+" Name: "+rs.getString(2)+" Num: "+rs.getString(3)+" Add: "+rs.getString(4));
//                }
            } catch (SQLException ex) {
                System.out.println("Something went wrong. Please contact the developer with these details: "+ex);
            }
            nameTxt.setText("");
            idTxt.setText("");
            addTxt.setText("");
            phnTxt.setText("");
            displayTable(rs);
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        // TODO add your handling code here:
        idLabel.setVisible(true);
        idTxt.setVisible(true);
        nameLabel.setVisible(true);
        nameTxt.setVisible(true);
        addLabel.setVisible(true);
        addTxt.setVisible(true);
        phnLabel.setVisible(true);
        phnTxt.setVisible(true);
        submitBtn.setVisible(true);
        submitBtn.setText("Insert");
        homeBtn.setVisible(true);
        jScrollPane1.setVisible(true);
        
        madeByLabel.setVisible(false);
        insertBtn.setVisible(false);
        deleteBtn.setVisible(false);
        updateBtn.setVisible(false);
        searchBtn.setVisible(false);
    }//GEN-LAST:event_insertBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        idLabel.setVisible(true);
        idTxt.setVisible(true);
        nameLabel.setVisible(true);
        nameTxt.setVisible(true);
        addLabel.setVisible(true);
        addTxt.setVisible(true);
        phnLabel.setVisible(true);
        phnTxt.setVisible(true);
        submitBtn.setVisible(true);
        homeBtn.setVisible(true);
        submitBtn.setText("Update");
        jScrollPane1.setVisible(true);
        
        madeByLabel.setVisible(false);
        insertBtn.setVisible(false);
        deleteBtn.setVisible(false);
        updateBtn.setVisible(false);
        searchBtn.setVisible(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        nameLabel.setVisible(true);
        nameTxt.setVisible(true);
        idLabel.setVisible(true);
        idTxt.setVisible(true);
        phnLabel.setVisible(true);
        phnTxt.setVisible(true);
        addLabel.setVisible(true);
        addTxt.setVisible(true);
        submitBtn.setVisible(true);
        submitBtn.setText("Search");
        homeBtn.setVisible(true);
        jScrollPane1.setVisible(true);
        
        madeByLabel.setVisible(false);
        insertBtn.setVisible(false);
        deleteBtn.setVisible(false);
        updateBtn.setVisible(false);
        searchBtn.setVisible(false);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        idLabel.setVisible(false);
        idTxt.setVisible(false);
        nameLabel.setVisible(false);
        nameTxt.setVisible(false);
        phnLabel.setVisible(false);
        phnTxt.setVisible(false);
        addLabel.setVisible(false);
        addTxt.setVisible(false);
        submitBtn.setVisible(false);
        homeBtn.setVisible(false);
        jScrollPane1.setVisible(false);
        
        madeByLabel.setVisible(true);
        insertBtn.setVisible(true);
        deleteBtn.setVisible(true);
        updateBtn.setVisible(true);
        searchBtn.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetailsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addTxt;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel madeByLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phnLabel;
    private javax.swing.JTextField phnTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
